### PR TITLE
Add demo that implements requesting user input while using the router

### PR DESCRIPTION
**Pull request by shaned24**
The goal of this PR was to add a demo route that adds support for requesting user input, the code must wait asynchronously and timeout at a sensible duration (10 seconds for this demo)

- This PR adds a demo that requests user input.
- The routing struct also has support for configuring the request input timeout

### CODE REVIEW

**Comment by shaned24** [comment]
@MostHated for visibility

**Comment by MostHated** [comment]
Good stuff!

I was speaking with someone about this before, I believe it was the dev of Disgord. He mentioned something about possible issues with taking input if more than one user is trying to send input to the bot at once, something having to do with cycling through the messages repeatedly? I was unfortunately not really sure how to go about implementing that, so I never moved my bot into a stage to release yet in fear of a bug I might not know how to fix yet. 

Do you think that something like that might become an issue if, say 2-5 people might be communicating with the bot at the same time sending input to it? I thought about trying to open several discord sessions at once to try and just see what ends up happening, but I am not sure that would work out great, lol.

Thanks for this though man, appreciated!
-MH

**Comment by shaned24** [comment]
@MostHated I think it might depend on the context of the message being sent either as a direct message or in a group channel, I have a feeling direct messages might be fine as this particular implementation scopes in on a user channel rather than a group.

**Comment by shaned24** [comment]
I just did a test with 2 sessions and it worked fine, however with murphys law on our side anything can and will go wrong :D

**Comment by MostHated** [comment]
All communication with my bot is going to be via PM's. It is a utility bot to let people who purchased a Unity3d asset prove that they bought it by providing an invoice number. So none of it needs to be in a public channel anyways. But... that is indeed true, lol. Murphy's law takes no sick days. 

Hmm... or does it? That makes me wonder since that would technically prove Murphy's law even further. Anyways... >_< Thanks again, lol.
-MH

**Comment by shaned24** [comment]
Thats pretty cool, is the invoice number tied to the discord user in any way?

**Comment by MostHated** [comment]
It is once they run through the process. I save it to a database along with their email. I also integrated it with WordPress so that once it is verified they can gain access to special/restricted content, or whatever someone wishes that requires a specific role.

**Pull request merged**
